'''f=open("text.txt","r+")
for i in range(5):
    n=input("Enter any line of text")
    f.write(n)
print("Data written")
f.seek(0)
#f.close()
#f=open("text.txt","r")
a=f.read()
print(a,type(a))
f.close()
'''
f=open("Text.txt",'r+')
a=eval(input("Enter a list on line you want to write"))
f.writelines(a)
f.close()
f=open("Text.txt","r")
a=f.read()
print(a,type(a))
f.close()
